### ISSUE TITLE
Deploys to github pages fails

### ISSUE THREAD

**Issue by jaymiejones86** [thoughtbot/proteus-jekyll#15]
The gh-pages branch that is created will only display the initial commit made by joshuaogle as seen http://pixelstack.github.io/pixelstack.com/

Is there any reason for this at all? This is not my first time deploying jekyll or middleman sites, but for some reason I cannot deploy with the `proteus deploy` command.

Any help would be greatly appreciated.

**Comment by nysthee** [comment]
Did you manage to fix this?

**Comment by jaymiejones86** [comment]
Hi @nysthee,

Sorry, I forgot to update this issue.
I would not quite call it a fix, but what I ended up doing was completely destroying the .git dir and re-initializing it. That worked.

Maybe during the setup there can be a command to remove and create a new repo?

**Comment by nysthee** [comment]
Thanks for the answer. I ended up using the octopress gem witch supports
Jekyll deployment.

https://github.com/octopress/deploy

2015-05-11 10:42 GMT+02:00 Jaymie Jones <notifications@github.com>:

**Comment by timup** [comment]
```build/``` needs to be removed from ```.gitignore``` then added to tracking for this to work.

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
