### ISSUE TITLE
Question: why bourbon and neat are configured as plugins?

### ISSUE THREAD

**Issue by exalted** [thoughtbot/proteus-jekyll#20]
[Line 1 of `_config.yml`](https://github.com/thoughtbot/proteus-jekyll/blob/1e4a9afa5b5d75317fa0d09e4dec7be39531fdc0/_config.yml#L1) contains `gems: [bourbon, neat]`. As far as I know `gems` is for jekyll plugins, and although I am not sure what a plug-in is in this context, I wonder what does either `bourbon` or `neat` add/alter to jekyll?

My understanding is that bourbon and neat should work just fine without that line.

Any ideas please?

**Comment by joshuaogle** [comment]
@exalted Without that line, Jekyll doesn't put the files in the pipeline for importing. You get:
```
Liquid Exception: File to import not found or unreadable: bourbon
```

Bourbon (http://bourbon.io) and Neat(http://neat.bourbon.io) add very useful Sass mixins and a Sass grid system. It's a big part of our process here at thoughtbot and they go in virtually all of our projects. If you want to use something else, it's as easy as removing that line in `_config.yml`, the references in the `Gemfile` and the imports in the css/js.

**Comment by joshuaogle** [comment]
Almost forgot I wrote a more detailed guide for removing them if you like: https://github.com/thoughtbot/proteus-jekyll/wiki/Removing-the-Bourbon-Suite

**Comment by exalted** [comment]
@joshuaogle thanks for quick answer. I wonder though, if I were to use GitHub’s own auto-build feature for pages (meaning no manual `jekyll build`), since GitHub Pages currently supports only a [handful number of plugins](https://help.github.com/articles/using-jekyll-plugins-with-github-pages/), does that mean it simply wouldn’t work?

**Comment by exalted** [comment]
I guess I should be including bourbon and neat manually instead of installing as gems...

**Comment by joshuaogle** [comment]
@exalted That's something I haven't tried yet, but I'd like to try to find a solution. I think you're right that the solution in that case is probably to just download them and include them locally. It would be harder to keep updated, but not the worst thing in the world.

**Comment by exalted** [comment]
> Almost forgot I wrote a more detailed guide for removing them if you like: https://github.com/thoughtbot/proteus-jekyll/wiki/Removing-the-Bourbon-Suite

I guess that page is missing removal of relevant parts from `_config.yml`.

**Comment by exalted** [comment]
> but I'd like to try to find a solution.

I believe there’s no solution really, since GitHub won’t allow custom plugins in their build process.
