### ISSUE TITLE
Jekyll_Assets

### ISSUE THREAD

**Issue by AndrewCull** [thoughtbot/proteus-jekyll#22]
Thank you for building this, it's a great prototyping tool, it's been working fine until a recent gem update of my system.  It's seems jekyll_assets and autoprefixer is incompatable causing an issue which throws the following error:

```
 Liquid Exception: wrong number of arguments (3 for 1..2) in _layouts/default.html
/.rvm/gems/ruby-2.0.0-p247/gems/autoprefixer-rails-6.0.3/lib/autoprefixer-rails.rb:17:in `install': wrong       number of arguments (3 for 1..2) (ArgumentError)
from /.rvm/gems/ruby-2.0.0-p247/gems/jekyll-assets-autoprefixer
1.0.0.pre.alpha3/lib/jekyll/assets/autoprefixer.rb:19:in `block in setup!'
```

I modified the gemfile to install jekyll-assets 1.0.0 to no avail and still playing with it, unless anyone knows the answer.

**Comment by AndrewCull** [comment]
Changed the gem file, and added bitters for extra credit.

Delete:
```
group :jekyll_plugins do
  gem 'jekyll-assets-autoprefixer'
end
```

Add
```
gem 'autoprefixer-rails'
gem 'bitters'
```

Back in action.

**Comment by joshuaogle** [comment]
@AndrewCull Glad you got it! I investigated this a little and it was working for me, but I'll check out `autoprefixer-rails` to see if that's a better fit.

**Comment by AndrewCull** [comment]
Thank you @joshuaogle.
