### ISSUE TITLE
bowersync or livereload?

### ISSUE THREAD

**Issue by Sananes** [thoughtbot/proteus-jekyll#24]
Hey guys, anyway you could include bowersync or livereload to this repository?

Thanks!

**Comment by Sananes** [comment]
I ended up creating my own gulp file for the workdlow

**Comment by joshuaogle** [comment]
The usual way to do Livereload with Jekyll is to use Guard, but you're effectively getting the same thing with Gulp. I am still looking into simple solutions for how to do this since we do have it in the Middleman kit. I'm glad Gulp works out for your project, it's great for all sorts of things
